### ISSUE TITLE
setup.py build error on macOS 10.13+

### ISSUE THREAD

**Issue by fredericpoitevin** [Eigenstate/vmd-python#19]
Hi, compilation does not work on macOS 10.13+ with error 
```PythonTextInterp.C:30:10: fatal error: 'Python/errcode.h' file not found #include "Python/errcode.h"```

Quick fix was to comment out a few lines around l.30 in`vmd-python/vmd/vmd_src/src/PythonTextInterp.C`:
```
//#if defined(__APPLE__)
// use the Apple-provided Python framework
//#include "Python/errcode.h"
//#else
#include "errcode.h"
//#endif
```
